### ISSUE TITLE
상세보기 요청 시 조회수 증가 안되는 이슈

### ISSUE THREAD

**Issue by jjangsky** [two-clock/backend#104]
현재 상세보기 API가 최초에는 DB 접근을 하지만 그 이후에 특정 시간 동안 캐시 데이터를 불러오고 있습니다.
상세보기 로직 중 조회 수 증가 로직이 포함되어 있어 캐시 데이터를 불러올 경우 해당 로직이 실행이 되고 있지 않아서 
이슈가 발생하였습니다~

**Comment by openmpy** [comment]
@jjangsky 님
조회하는 로직을 따로 분리하거나 아니면 비동기로 처리하면 될거 같은데 어떻게 생각하시나요?

**Comment by jjangsky** [comment]
@openmpy 그래서 조회수 증가 서비스 로직을 따로 분리하려고 생각하였습니다.

아무래도 상세보기 데이터가 캐싱되어 있다보니까 실시간으로 조회수를 맞춰주는데 어려움이 있을 것 같네요
-> 사실 가능은 하지만 증가된 조회 수를 계속 가져오다보니 캐싱한 의미가 없어지지 않을까 싶습니다.

비동기처리 방식은 조회 API와 조회수 증가API 분리하여 두 번 요청하는 방식으로 생각하신걸까요??

**Comment by openmpy** [comment]
@jjangsky 님
아뇨아뇨 한번의 요청입니다.
응답 값은 캐싱 된 데이터를 반환 해주고 비동기적으로 조회수를 증가 처리하면 되지 않을까 싶습니다.
