### ISSUE TITLE
개인 프로필 수정

### ISSUE THREAD

**Issue by openmpy** [two-clock/backend#32]
> 1. 사용자는 로그인 상태여야 함.
> 2. 수정 후 변경 사항은 즉시 반영되어야 함.
> 3. 프로필 사진은 최대 5MB 이하의 파일만 업로드 가능.
> 4. 모든 필드는 필수 입력 사항이 아님.

@jjangsky 님~
개인 프로필 수정 기능을 만들려고 했으나.. 결론부터 말하자면 안됩니다.
프로필 아이디나 이미지는 수정할 수 있는 GitHub API 자체가 존재하지 않고.. 이름, 자기소개 같은 내용도 403 이 떠서 수정할 수가 없습니다.
사용자들이 GitHub 들어가서 직접 수정하는 방법 외에는 없는거 같습니다.

**Comment by jjangsky** [comment]
@openmpy 님 상심이 크시겠읍니다 ㅜㅜ
