### ISSUE TITLE
docs: GitConnect 1차 논리 모델링

### ISSUE THREAD

**Issue by jjangsky** [two-clock/backend#7]
@openmpy 님 바쁘신 와중에 의견이 필요하여 이슈사항에 올립니다.

### 1차 논리 모델링
![image](https://github.com/user-attachments/assets/97915bd9-525d-43b9-b71e-5a58b7d333b0)

프로젝트 주요 기능을 중심으로 논리 모델링을 작성해 보았습니다.

회원 Entity는 Github Oauth를 사용 예정인지라 어떻게 구성이 될지 파악이 불가능하여
간단하게 테이블만 구성하여 이점 양해 부탁드립니다.

일단 1차 논리 모델링이라 대충 생각나는 대로 그려 보았습니다.
관계 설정 여부 및 Entity 컬럼에 대한 피드백 부탁드리겠습니다 !

추가적으로 카테고리 테이블 존재 여부에 대한 생각이 궁금합니다.

**Comment by openmpy** [comment]
> @openmpy 님 바쁘신 와중에 의견이 필요하여 이슈사항에 올립니다.
> 
> ### 1차 논리 모델링
> ![image](https://private-user-images.githubusercontent.com/103441154/352145651-97915bd9-525d-43b9-b71e-5a58b7d333b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NzY3MjgsIm5iZiI6MTcyMTk3NjQyOCwicGF0aCI6Ii8xMDM0NDExNTQvMzUyMTQ1NjUxLTk3OTE1YmQ5LTUyNWQtNDNiOS1iNzFlLTVhNThiN2QzMzNiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQwNjQ3MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OWZjZDM4MWI4ZDU1YWRlZDZmODBhNTQwMTZhNzY5NzE1ZDc4MjI3ZjAxYzg0YTk1N2FlOTk2MjIxMjA1ZmZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9petPDCamTc0DvsXfWAeT5ChBqQtJWzkfZLGSmUi_Q0)
> 
> 프로젝트 주요 기능을 중심으로 논리 모델링을 작성해 보았습니다.
> 
> 회원 Entity는 Github Oauth를 사용 예정인지라 어떻게 구성이 될지 파악이 불가능하여 간단하게 테이블만 구성하여 이점 양해 부탁드립니다.
> 
> 일단 1차 논리 모델링이라 대충 생각나는 대로 그려 보았습니다. 관계 설정 여부 및 Entity 컬럼에 대한 피드백 부탁드리겠습니다 !
> 
> 추가적으로 카테고리 테이블 존재 여부에 대한 생각이 궁금합니다.

@jjangsky 님 피드백 남겨봅니다.
우선 ``회원`` 테이블에는 ``아이디``, ``프로필 이미지 URL``, ``이름`` 필드가 추가되면 좋을거 같습니다.
``아이디`` 필드는 ``사용자 토큰``으로 대체할 수 있을거 같습니다.
``사용자 로그인 로그`` 테이블에는 ``IP`` 필드가 추가되면 좋을거 같습니다.

``사용자 페이지 뷰 로그`` 테이블이 정확히 어떤 역할을 하는지 궁금합니다.
필드만 보면 카테고리별 페이지 뷰를 나타내는거 같은데 이런 의도로 설계하신 테이블 맞을까요?

다음으로 카테고리 테이블 존재 여부에 대해서는 굳이? 싶은 생각이 듭니다.
여러 카테고리 종류가 존재하는 것도 아니고 추가 될 일도 거의 없다고 봅니다.
그래서 테이블을 따로 만들지 않고 작성해주신 게시판 종류(카테고리 코드)를 Enum 타입으로 진행해도 충분할거 같습니다.

---

[GitHub API 코드 샘플](https://docs.github.com/ko/rest/users/users?apiVersion=2022-11-28#get-a-user-using-their-id)

**Comment by jjangsky** [comment]
@openmpy 님 자세한 피드백 감사드립니다~ 

말씀하신대로 회원 필드에 관련하여 피드백 반영 후 [notion](jjangsky.notion.stie) 에 올려놓겠습니다.

페이지뷰는 @openmpy 님이 생각하신 의도로 생성한 것이 맞습니다 !
현재 계획에는 없지만 이후 프로젝트 확장성을 고려하여 관리자 프로젝트나 통계 데이터 추출을 위해 일단 수집하는 것이 좋을 것 같아서 추가해 보았습니다.

프로메테우스나 그라파나를 사용하여 메트릭 수집 후 모니터링이 가능한 것으로 알고 있으나 이러한 통계 데이터는 DB에 직접 저장하여 이후 통계 지표나 다양한 데이터를 만들 때 도움이되지 않을까 싶어서 추가하였습니다.
- 프로젝트를 개발할 때 데이터 수집만 목적으로 두고 이후 2차, 3차 프로젝트가 진행된다는 가정 하에 데이터가 있으면 좋을것 같아서 넣어봤습니다.

카테고리 관련 하여 통일성 있게 전부 `Enum Type` 으로 관리하는 것으로 알겠습니다.

귀중한 시간 내주셔서 감사합니다 👍

**Comment by openmpy** [comment]
> @openmpy 님 자세한 피드백 감사드립니다~ 
> 
> 
> 
> 말씀하신대로 회원 필드에 관련하여 피드백 반영 후 [notion](jjangsky.notion.stie) 에 올려놓겠습니다.
> 
> 
> 
> 페이지뷰는 @openmpy 님이 생각하신 의도로 생성한 것이 맞습니다 !
> 
> 현재 계획에는 없지만 이후 프로젝트 확장성을 고려하여 관리자 프로젝트나 통계 데이터 추출을 위해 일단 수집하는 것이 좋을 것 같아서 추가해 보았습니다.
> 
> 
> 
> 프로메테우스나 그라파나를 사용하여 메트릭 수집 후 모니터링이 가능한 것으로 알고 있으나 이러한 통계 데이터는 DB에 직접 저장하여 이후 통계 지표나 다양한 데이터를 만들 때 도움이되지 않을까 싶어서 추가하였습니다.
> 
> - 프로젝트를 개발할 때 데이터 수집만 목적으로 두고 이후 2차, 3차 프로젝트가 진행된다는 가정 하에 데이터가 있으면 좋을것 같아서 넣어봤습니다.
> 
> 
> 
> 카테고리 관련 하여 통일성 있게 전부 `Enum Type` 으로 관리하는 것으로 알겠습니다.
> 
> 
> 
> 귀중한 시간 내주셔서 감사합니다 👍 
> 
> 
> 
> 
> 
> 

@jjangsky 님 고생 많으셨습니다 ~
작성해주신 ERD 바탕으로 작업 진행 하겠습니다.
해당 이슈는 닫도록 하겠습니다.
